name:                class1
version:             0.1.0.0
github:              "mrlucasrib/functional-programming/class1"
license:             BSD3
author:              "Lucas Ribeiro"
maintainer:          "lucas.mr@aluno.ufop.edu.br"
copyright:           "2021 Lucas Moreira"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mrlucasrib/functional-programming/class1#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  class1-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - class1

tests:
  class1-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - class1
